url=jdbc:postgresql://127.0.0.1:15432/apnafund

username=apnafund_ai_dev_deploy

defaultSchemaName=apnafundaidev
appSchema=apnafundaidev
liquibase.liquibaseSchemaName=apnafundaidev

changeLogFile=resources/db/changelog/db.changelog-ec2aimaster.yaml