url=jdbc:postgresql://127.0.0.1:15432/apnafund

username=apnafund_admin

defaultSchemaName=public
appSchema=apnafundaidev
liquibase.liquibaseSchemaName=public

changeLogFile=resources/db/changelog/db.changelog-ec2aimaster.yaml
databaseChangeLogTableName=databasechangelog_ai
databaseChangeLogLockTableName=databasechangeloglock_ai