searchPath=server/src/main/resources/db
url=jdbc:postgresql://127.0.0.1:5432/ApnaFund?currentSchema=%22ApnaFundTest%22
username=apnafund_test_user
password=apna@testu3er
defaultSchemaName=ApnaFundTest
appSchemaName=ApnaFundTest
liquibaseSchemaName=ApnaFundTest
preserveSchemaCase=true
classpath=.
changeLogFile=changelog/baseline/000-initial-baseline.yaml
# this sets the ${schemaName} property used in SQL files:
liquibase.hub.mode=off
