-- BEGIN;
-- Database: ApnaFund

-- DROP DATABASE IF EXISTS "ApnaFund";


CREATE TABLE  IF NOT EXISTS "users" (
  "userId"             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName"          TEXT    NOT NULL,
  "lastName"           TEXT,
  "emailId"            TEXT    NOT NULL,
  "phoneNumber"        TEXT,
  "status"             TEXT    NOT NULL,
  "passwordHash"       TEXT,
  "createdDate"        TEXT    NOT NULL,  -- kept as TEXT (Room style)
  "isPinSet"           BOOLEAN DEFAULT false,
  "hashPIN"            TEXT,
  "firebaseUserId"     TEXT,
  "userCode"           TEXT    NOT NULL
);

CREATE TABLE  IF NOT EXISTS "roles" (
  "roleId"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roleCode"          TEXT    NOT NULL,
  "roleDescription"   TEXT,
  "status"            TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS "type" (
  "typeId"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "typeCode"         TEXT    NOT NULL,
  "typeDescription"  TEXT    NOT NULL,
  "status"           TEXT    NOT NULL,

 CONSTRAINT "uq_type_code" UNIQUE ("typeCode")
);

CREATE TABLE IF NOT EXISTS "privilege" (
  "privilegeId"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "privilegeCode"         TEXT    NOT NULL,
  "privilegeDescription"  TEXT,
  "status"                TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS "groups" (
  "groupId"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "groupName"    TEXT    NOT NULL,
  "moderator"    INTEGER,
  "createdDate"  TEXT    NOT NULL,
  "description"  TEXT,
  "groupCode"    TEXT    NOT NULL,
  "status"       TEXT    NOT NULL,
  CONSTRAINT "fk_groups_moderator_users"
    FOREIGN KEY ("moderator") REFERENCES "users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "user_roles" (
  "userRoleId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"      INTEGER NOT NULL,
  "roleId"      INTEGER NOT NULL,
  "status"      TEXT    NOT NULL,
  CONSTRAINT "fk_user_roles_user"
    FOREIGN KEY ("userId") REFERENCES "users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_user_roles_role"
    FOREIGN KEY ("roleId") REFERENCES "roles" ("roleId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "role_privilege" (
  "rolePrivilegeId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "privilegeId"      INTEGER NOT NULL,
  "roleId"           INTEGER NOT NULL,
  "status"           TEXT    NOT NULL,
  CONSTRAINT "fk_role_privilege_role"
    FOREIGN KEY ("roleId") REFERENCES "roles" ("roleId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_role_privilege_priv"
    FOREIGN KEY ("privilegeId") REFERENCES "privilege" ("privilegeId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "group_members" (
  "groupMemberId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"         INTEGER NOT NULL,
  "groupId"        INTEGER NOT NULL,
  "joiningDate"    TEXT    NOT NULL,
  CONSTRAINT "fk_group_members_group"
    FOREIGN KEY ("groupId") REFERENCES "groups" ("groupId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_group_members_user"
    FOREIGN KEY ("userId") REFERENCES "users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "uq_group_members_user_group" UNIQUE ("userId","groupId")
);

CREATE TABLE IF NOT EXISTS "funds" (
  "fundId"                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fundName"                TEXT              NOT NULL,
  "fundStartDate"           TEXT              NOT NULL,
  "fundMaturityDate"        TEXT              NOT NULL,
  "fundPeriod"              DOUBLE PRECISION  NOT NULL,
  "depositionFrequency"     TEXT              NOT NULL,
  "moderator"               INTEGER           NOT NULL,
  "recurringDepositAmount"  DOUBLE PRECISION  NOT NULL,
  "fundStatus"              TEXT              NOT NULL,
  "loanInterestRate"        DOUBLE PRECISION  NOT NULL,
  "lateFeeRate"             DOUBLE PRECISION  NOT NULL,
  "monthlyDepDateBy"        INTEGER           NOT NULL,
  "groupId"                 INTEGER           NOT NULL,
  "fundCode"                TEXT              NOT NULL,
  CONSTRAINT "fk_funds_group"
    FOREIGN KEY ("groupId") REFERENCES "groups" ("groupId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "fund_details" (
  "fundDetailsId"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fundId"                            INTEGER           NOT NULL,
  "totalExpectedDeposit"              DOUBLE PRECISION  NOT NULL,
  "totalCurrentDeposit"               DOUBLE PRECISION  NOT NULL,
  "totalCurrentLateFee"               DOUBLE PRECISION  NOT NULL,
  "totalCurrentInterestCollected"     DOUBLE PRECISION  NOT NULL,
  "totalExpectedMaturityAmount"       DOUBLE PRECISION  NOT NULL,
  "totalCurrAmount"                   DOUBLE PRECISION  NOT NULL,
  CONSTRAINT "fk_fund_details_fund"
    FOREIGN KEY ("fundId") REFERENCES "funds" ("fundId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "deposits" (
  "depositId"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "depositorId"     INTEGER           NOT NULL,
  "depositedDate"   TEXT              NOT NULL,
  "depositAmount"   DOUBLE PRECISION  NOT NULL,
  "depositMonth"    TEXT              NOT NULL,
  "depositYear"     TEXT              NOT NULL,
  "fundId"          INTEGER           NOT NULL,
  "lateFee"         DOUBLE PRECISION,
  CONSTRAINT "fk_deposits_fund"
    FOREIGN KEY ("fundId") REFERENCES "funds" ("fundId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "fund_members" (
  "fundMemberId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"        INTEGER NOT NULL,
  "fundId"        INTEGER NOT NULL,
  "joiningDate"   TEXT    NOT NULL,
  CONSTRAINT "fk_fund_members_fund"
    FOREIGN KEY ("fundId") REFERENCES "funds" ("fundId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_fund_members_user"
    FOREIGN KEY ("userId") REFERENCES "users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'uq_fund_members_user_fund'
    AND conrelid = 'fund_members'::regclass
  ) THEN
    ALTER TABLE fund_members
      ADD CONSTRAINT uq_fund_members_user_fund
      UNIQUE ("userId","fundId");
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS "loans" (
  "loanId"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "loanNumber"     TEXT              NOT NULL,
  "borrowerId"     INTEGER           NOT NULL,
  "issuedDate"     TEXT              NOT NULL,
  "period"         DOUBLE PRECISION  NOT NULL,
  "loanAmount"     DOUBLE PRECISION  NOT NULL,
  "maturityDate"   TEXT              NOT NULL,
  "rateOfInterest" DOUBLE PRECISION  NOT NULL,
  "status"         TEXT              NOT NULL,
  "fundId"         INTEGER           NOT NULL,
  CONSTRAINT "fk_loans_fund"
    FOREIGN KEY ("fundId") REFERENCES "funds" ("fundId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "loan_details" (
  "loanDetailsId"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "loanId"          INTEGER           NOT NULL,
  "origPrincipal"   DOUBLE PRECISION  NOT NULL,
  "totalInterest"   DOUBLE PRECISION  NOT NULL,
  "totalAmount"     DOUBLE PRECISION  NOT NULL,
  "emiInterest"     DOUBLE PRECISION  NOT NULL,
  "currTotalIntPaid" DOUBLE PRECISION NOT NULL,
  "currPrincipal"   DOUBLE PRECISION  NOT NULL,
  CONSTRAINT "fk_loan_details_loan"
    FOREIGN KEY ("loanId") REFERENCES "loans" ("loanId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "loan_emi" (
  "loanEmiId"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "loanId"             INTEGER           NOT NULL,
  "emiMonth"           TEXT              NOT NULL,
  "emiYear"            TEXT              NOT NULL,
  "emiDepositedDate"   TEXT              NOT NULL,
  "emiDepositedAmount" DOUBLE PRECISION  NOT NULL,
  "prepaymentAmount"   DOUBLE PRECISION  NOT NULL,
  "lateFee"            DOUBLE PRECISION  NOT NULL,
  CONSTRAINT "fk_loan_emi_loan"
    FOREIGN KEY ("loanId") REFERENCES "loans" ("loanId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "user_notifications" (
  "userNotificationId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notificationType"    TEXT    NOT NULL,
  "userId"              INTEGER NOT NULL,
  "message"             TEXT,
  "isExpiredFlag"       INTEGER NOT NULL,
  "publishedFlag"       INTEGER NOT NULL,
  "readFlag"            INTEGER NOT NULL,
  "status"              TEXT    NOT NULL,
  CONSTRAINT "fk_user_notifications_user"
    FOREIGN KEY ("userId") REFERENCES "users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_user_notifications_type"
    FOREIGN KEY ("notificationType") REFERENCES "type" ("typeCode")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "user_password_history" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"       INTEGER NOT NULL,
  "passwordHash" TEXT    NOT NULL,
  "changedAt"    BIGINT NOT NULL DEFAULT ((extract(epoch FROM now()) * 1000)::BIGINT),
  CONSTRAINT "fk_user_pwd_hist_user"
    FOREIGN KEY ("userId") REFERENCES "users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "user_pin_history" (
  "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"    INTEGER NOT NULL,
  "pinHash"   TEXT    NOT NULL,
  "changedAt" BIGINT NOT NULL DEFAULT ((extract(epoch FROM now()) * 1000)::BIGINT),
  CONSTRAINT "fk_user_pin_hist_user"
    FOREIGN KEY ("userId") REFERENCES "users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "feedbacks" (
  "feedbackId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"      INTEGER NOT NULL,
  "message"     TEXT    NOT NULL,
  "timestamp"   TEXT    NOT NULL
);

