-- CREATE DATABASE "ApnaFund" WITH OWNER = postgres ENCODING 'UTF8';

-- Ensure schema exists
CREATE SCHEMA IF NOT EXISTS "ApnaFund";

BEGIN;

-- Drops (indexes first)
DROP INDEX IF EXISTS "ApnaFund"."index_type_typeCode";

-- Children / dependents
DROP TABLE IF EXISTS "ApnaFund"."loan_emi";
DROP TABLE IF EXISTS "ApnaFund"."loan_details";
DROP TABLE IF EXISTS "ApnaFund"."user_password_history";
DROP TABLE IF EXISTS "ApnaFund"."user_pin_history";
DROP TABLE IF EXISTS "ApnaFund"."user_notifications";
DROP TABLE IF EXISTS "ApnaFund"."deposits";
DROP TABLE IF EXISTS "ApnaFund"."fund_details";
DROP TABLE IF EXISTS "ApnaFund"."fund_members";
DROP TABLE IF EXISTS "ApnaFund"."loans";
DROP TABLE IF EXISTS "ApnaFund"."user_roles";
DROP TABLE IF EXISTS "ApnaFund"."role_privilege";
DROP TABLE IF EXISTS "ApnaFund"."group_members";

-- Parents
DROP TABLE IF EXISTS "ApnaFund"."funds";
DROP TABLE IF EXISTS "ApnaFund"."groups";
DROP TABLE IF EXISTS "ApnaFund"."privilege";
DROP TABLE IF EXISTS "ApnaFund"."roles";
DROP TABLE IF EXISTS "ApnaFund"."type";
DROP TABLE IF EXISTS "ApnaFund"."feedbacks";
DROP TABLE IF EXISTS "ApnaFund"."users";

COMMIT;

BEGIN;

CREATE TABLE "ApnaFund"."users" (
  "userId"             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName"          TEXT    NOT NULL,
  "lastName"           TEXT,
  "emailId"            TEXT    NOT NULL,
  "phoneNumber"        TEXT,
  "status"             TEXT    NOT NULL,
  "passwordHash"       TEXT,
  "createdDate"        TEXT    NOT NULL,
  "isPinSet"           BOOLEAN DEFAULT false,
  "hashPIN"            TEXT,
  "firebaseUserId"     TEXT,
  "userCode"           TEXT    NOT NULL
);

ALTER TABLE "ApnaFund"."users"
  ADD CONSTRAINT users_emailid_key UNIQUE ("emailId");

CREATE TABLE "ApnaFund"."roles" (
  "roleId"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roleCode"          TEXT    NOT NULL,
  "roleDescription"   TEXT,
  "status"            TEXT    NOT NULL
);

CREATE TABLE "ApnaFund"."type" (
  "typeId"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "typeCode"         TEXT    NOT NULL,
  "typeDescription"  TEXT    NOT NULL,
  "status"           TEXT    NOT NULL
);

CREATE UNIQUE INDEX "ApnaFund"."index_type_typeCode"
  ON "ApnaFund"."type" ("typeCode");

CREATE TABLE "ApnaFund"."privilege" (
  "privilegeId"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "privilegeCode"         TEXT    NOT NULL,
  "privilegeDescription"  TEXT,
  "status"                TEXT    NOT NULL
);

CREATE TABLE "ApnaFund"."groups" (
  "groupId"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "groupName"    TEXT    NOT NULL,
  "moderator"    INTEGER,
  "createdDate"  TEXT    NOT NULL,
  "description"  TEXT,
  "groupCode"    TEXT    NOT NULL,
  "status"       TEXT    NOT NULL,
  CONSTRAINT "fk_groups_moderator_users"
    FOREIGN KEY ("moderator")
    REFERENCES "ApnaFund"."users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
  CONSTRAINT "uq_group_members_user_group" UNIQUE ("userId","groupId")
);

CREATE TABLE "ApnaFund"."user_roles" (
  "userRoleId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"      INTEGER NOT NULL,
  "roleId"      INTEGER NOT NULL,
  "status"      TEXT    NOT NULL,
  CONSTRAINT "fk_user_roles_user"
    FOREIGN KEY ("userId")
    REFERENCES "ApnaFund"."users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_user_roles_role"
    FOREIGN KEY ("roleId")
    REFERENCES "ApnaFund"."roles" ("roleId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."role_privilege" (
  "rolePrivilegeId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "privilegeId"      INTEGER NOT NULL,
  "roleId"           INTEGER NOT NULL,
  "status"           TEXT    NOT NULL,
  CONSTRAINT "fk_role_privilege_role"
    FOREIGN KEY ("roleId")
    REFERENCES "ApnaFund"."roles" ("roleId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_role_privilege_priv"
    FOREIGN KEY ("privilegeId")
    REFERENCES "ApnaFund"."privilege" ("privilegeId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."group_members" (
  "groupMemberId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"         INTEGER NOT NULL,
  "groupId"        INTEGER NOT NULL,
  "joiningDate"    TEXT    NOT NULL,
  CONSTRAINT "fk_group_members_group"
    FOREIGN KEY ("groupId")
    REFERENCES "ApnaFund"."groups" ("groupId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_group_members_user"
    FOREIGN KEY ("userId")
    REFERENCES "ApnaFund"."users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."funds" (
  "fundId"                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fundName"                TEXT              NOT NULL,
  "fundStartDate"           TEXT              NOT NULL,
  "fundMaturityDate"        TEXT              NOT NULL,
  "fundPeriod"              DOUBLE PRECISION  NOT NULL,
  "depositionFrequency"     TEXT              NOT NULL,
  "moderator"               INTEGER           NOT NULL,
  "recurringDepositAmount"  DOUBLE PRECISION  NOT NULL,
  "fundStatus"              TEXT              NOT NULL,
  "loanInterestRate"        DOUBLE PRECISION  NOT NULL,
  "lateFeeRate"             DOUBLE PRECISION  NOT NULL,
  "monthlyDepDateBy"        INTEGER           NOT NULL,
  "groupId"                 INTEGER           NOT NULL,
  "fundCode"                TEXT              NOT NULL,
  CONSTRAINT "fk_funds_group"
    FOREIGN KEY ("groupId")
    REFERENCES "ApnaFund"."groups" ("groupId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."fund_details" (
  "fundDetailsId"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fundId"                            INTEGER           NOT NULL,
  "totalExpectedDeposit"              DOUBLE PRECISION  NOT NULL,
  "totalCurrentDeposit"               DOUBLE PRECISION  NOT NULL,
  "totalCurrentLateFee"               DOUBLE PRECISION  NOT NULL,
  "totalCurrentInterestCollected"     DOUBLE PRECISION  NOT NULL,
  "totalExpectedMaturityAmount"       DOUBLE PRECISION  NOT NULL,
  "totalCurrAmount"                   DOUBLE PRECISION  NOT NULL,
  CONSTRAINT "fk_fund_details_fund"
    FOREIGN KEY ("fundId")
    REFERENCES "ApnaFund"."funds" ("fundId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."deposits" (
  "depositId"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "depositorId"     INTEGER           NOT NULL,
  "depositedDate"   TEXT              NOT NULL,
  "depositAmount"   DOUBLE PRECISION  NOT NULL,
  "depositMonth"    TEXT              NOT NULL,
  "depositYear"     TEXT              NOT NULL,
  "fundId"          INTEGER           NOT NULL,
  "lateFee"         DOUBLE PRECISION,
  CONSTRAINT "fk_deposits_fund"
    FOREIGN KEY ("fundId")
    REFERENCES "ApnaFund"."funds" ("fundId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."fund_members" (
  "fundMemberId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"        INTEGER NOT NULL,
  "fundId"        INTEGER NOT NULL,
  "joiningDate"   TEXT    NOT NULL,
  CONSTRAINT "fk_fund_members_fund"
    FOREIGN KEY ("fundId")
    REFERENCES "ApnaFund"."funds" ("fundId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_fund_members_user"
    FOREIGN KEY ("userId")
    REFERENCES "ApnaFund"."users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

ALTER TABLE "ApnaFund".fund_members
  ADD CONSTRAINT uq_fund_members_user_fund
  UNIQUE ("userId","fundId");

CREATE TABLE "ApnaFund"."loans" (
  "loanId"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "loanNumber"     TEXT              NOT NULL,
  "borrowerId"     INTEGER           NOT NULL,
  "issuedDate"     TEXT              NOT NULL,
  "period"         DOUBLE PRECISION  NOT NULL,
  "loanAmount"     DOUBLE PRECISION  NOT NULL,
  "maturityDate"   TEXT              NOT NULL,
  "rateOfInterest" DOUBLE PRECISION  NOT NULL,
  "status"         TEXT              NOT NULL,
  "fundId"         INTEGER           NOT NULL,
  CONSTRAINT "fk_loans_fund"
    FOREIGN KEY ("fundId")
    REFERENCES "ApnaFund"."funds" ("fundId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."loan_details" (
  "loanDetailsId"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "loanId"          INTEGER           NOT NULL,
  "origPrincipal"   DOUBLE PRECISION  NOT NULL,
  "totalInterest"   DOUBLE PRECISION  NOT NULL,
  "totalAmount"     DOUBLE PRECISION  NOT NULL,
  "emiInterest"     DOUBLE PRECISION  NOT NULL,
  "currTotalIntPaid" DOUBLE PRECISION NOT NULL,
  "currPrincipal"   DOUBLE PRECISION  NOT NULL,
  CONSTRAINT "fk_loan_details_loan"
    FOREIGN KEY ("loanId")
    REFERENCES "ApnaFund"."loans" ("loanId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."loan_emi" (
  "loanEmiId"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "loanId"             INTEGER           NOT NULL,
  "emiMonth"           TEXT              NOT NULL,
  "emiYear"            TEXT              NOT NULL,
  "emiDepositedDate"   TEXT              NOT NULL,
  "emiDepositedAmount" DOUBLE PRECISION  NOT NULL,
  "prepaymentAmount"   DOUBLE PRECISION  NOT NULL,
  "lateFee"            DOUBLE PRECISION  NOT NULL,
  CONSTRAINT "fk_loan_emi_loan"
    FOREIGN KEY ("loanId")
    REFERENCES "ApnaFund"."loans" ("loanId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."user_notifications" (
  "userNotificationId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notificationType"    TEXT    NOT NULL,
  "userId"              INTEGER NOT NULL,
  "message"             TEXT,
  "isExpiredFlag"       INTEGER NOT NULL,
  "publishedFlag"       INTEGER NOT NULL,
  "readFlag"            INTEGER NOT NULL,
  "status"              TEXT    NOT NULL,
  CONSTRAINT "fk_user_notifications_user"
    FOREIGN KEY ("userId")
    REFERENCES "ApnaFund"."users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "fk_user_notifications_type"
    FOREIGN KEY ("notificationType")
    REFERENCES "ApnaFund"."type" ("typeCode")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."user_password_history" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"       INTEGER NOT NULL,
  "passwordHash" TEXT    NOT NULL,
  "changedAt"    BIGINT NOT NULL DEFAULT ((extract(epoch FROM now()) * 1000)::BIGINT),
  CONSTRAINT "fk_user_pwd_hist_user"
    FOREIGN KEY ("userId")
    REFERENCES "ApnaFund"."users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."user_pin_history" (
  "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"    INTEGER NOT NULL,
  "pinHash"   TEXT    NOT NULL,
  "changedAt" BIGINT NOT NULL DEFAULT ((extract(epoch FROM now()) * 1000)::BIGINT),
  CONSTRAINT "fk_user_pin_hist_user"
    FOREIGN KEY ("userId")
    REFERENCES "ApnaFund"."users" ("userId")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "ApnaFund"."feedbacks" (
  "feedbackId"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"      INTEGER NOT NULL,
  "message"     TEXT    NOT NULL,
  "timestamp"   TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email_lower ON users ((lower("emailId")));

COMMIT;
