DROP TABLE IF EXISTS "approval_requests";

CREATE TABLE approval_requests (

    "approvalId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entityType" TEXT NOT NULL,
    "entityId" INT NOT NULL,
    "requestedBy" INT NOT NULL,
    "requestedAt" TIMESTAMPTZ DEFAULT NOW(),
    "approverUserId" INT NOT NULL,
    "approvalStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "decidedBy" INT NULL,
    "decidedAt" TIMESTAMPTZ NULL,
    "decisionReason" TEXT NULL,
    "status" TEXT DEFAULT 'ACTIVE'
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_single_pending_request
ON approval_requests("entityType","entityId")
WHERE "approvalStatus"='PENDING';

CREATE OR REPLACE FUNCTION create_loan_approval(
    p_loan_id INT,
    p_requested_by INT,
    p_approver INT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN

    INSERT INTO approval_requests(
        "entityType",
        "entityId",
        "requestedBy",
        "approverUserId"
    )
    VALUES (
        'LOAN',
        p_loan_id,
        p_requested_by,
        p_approver
    );

    UPDATE loans
    SET "workflowStatus"='PENDING_APPROVAL'
    WHERE "loanId"=p_loan_id;

    RETURN TRUE;

END;
$$;

CREATE OR REPLACE FUNCTION approve_loan_request(
    p_approval_id INT,
    p_approved_by INT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
DECLARE
    v_loan_id INT;
BEGIN

    SELECT "entityId"
    INTO v_loan_id
    FROM approval_requests
    WHERE "approvalId"=p_approval_id
      AND "approvalStatus"='PENDING';

    IF v_loan_id IS NULL THEN
        RETURN FALSE;
    END IF;

    UPDATE approval_requests
    SET
        "approvalStatus"='APPROVED',
        "approvedBy"=p_approved_by,
        "approvedAt"=NOW()
    WHERE "approvalId"=p_approval_id;

    UPDATE loans
    SET "workflowStatus"='APPROVED'
    WHERE "loanId"=v_loan_id;

    RETURN TRUE;

END;
$$;

CREATE OR REPLACE FUNCTION reject_loan_request(
    p_approval_id INT,
    p_rejected_by INT,
    p_reason TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
DECLARE
    v_loan_id INT;
BEGIN

    SELECT "entityId"
    INTO v_loan_id
    FROM approval_requests
    WHERE "approvalId"=p_approval_id
      AND "approvalStatus"='PENDING';

    IF v_loan_id IS NULL THEN
        RETURN FALSE;
    END IF;

    UPDATE approval_requests
    SET
        "approvalStatus"='REJECTED',
        "rejectedBy"=p_rejected_by,
        "rejectedAt"=NOW(),
        "rejectionReason"=p_reason
    WHERE "approvalId"=p_approval_id;

    UPDATE loans
    SET "workflowStatus"='REJECTED'
    WHERE "loanId"=v_loan_id;

    RETURN TRUE;

END;
$$;

CREATE OR REPLACE FUNCTION get_pending_approvals(
    p_user_id INT
)
RETURNS TABLE(
    approvalId INT,
    entityType TEXT,
    entityId INT,
    requesterName TEXT,
    createdAt TIMESTAMPTZ
)
LANGUAGE sql
AS $$
SELECT
    a."approvalId",
    a."entityType",
    a."entityId",
    u."firstName" || ' ' || u."lastName",
    a."requestedAt"
FROM approval_requests a
JOIN users u ON u."userId"=a."requestedBy"
WHERE a."approvalStatus"='PENDING'
AND a."approverUserId"=p_user_id;
$$;













